### ISSUE TITLE
Split/join nodes?

### ISSUE THREAD

**Issue by hardillb** [sciensa/node-red-contrib-scatter-gather#3]
Can you add something to the readme to explain how this differs from the built in split/join nodes?

**Comment by roalcantara** [comment]
Hi @hardillb, what's up?

I've just seen the answer from Dave C J on the [mailing list](https://groups.google.com/forum/#!topic/node-red/qsKiXt9mSoE) and it seems that the problem that I wanted to solve with this custom node can the done by using the manual mode of the Join Node (no Split Node needed).

After looking the Join Node more closely, I've come to the conclusion that the only real difference is that we need to set the "After a fixed number of messages" property in the Join Node, whereas by using the scatter/gather Nodes we don't need to set anything.

I don't know if the scatter/gather Nodes are still useful, after knowing about these great Join features.

I reckon that I might roll it back and unpublish it, eventually.

**Comment by roalcantara** [comment]
The library has been deprecated.
